name: Functions CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test_functions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions

    steps:
    - name: Checkout project
      uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'yarn'
        cache-dependency-path: 'yarn.lock'

    - name: Install dependencies
      run: yarn install

    - name: Run ESLint
      run: yarn lint
    
    - name: Run Prettier
      run: yarn prettier
    
    - name: Build
      run: yarn build
